;*******************************************************************************
;   File:       config.inc
;   Target:     PIC18F47K42
;   Description: Configuration bits for PIC18F47K42 Curiosity Nano
;*******************************************************************************

config FEXTOSC = OFF
config RSTOSC = HFINTOSC_64MHZ
config CLKOUTEN = OFF
config CSWEN = ON
config FCMEN = ON
config MCLRE = EXTMCLR
config PWRTS = PWRT_OFF
config MVECEN = ON
config IVT1WAY = ON
config LPBOREN = OFF
config BOREN = SBORDIS
config BORV = VBOR_2P45
config ZCD = OFF
config PPS1WAY = ON
config STVREN = ON
config XINST = OFF
config WDTCPS = WDTCPS_31
config WDTE = OFF
config WDTCWS = WDTCWS_7
config WDTCCS = SC
config BBSIZE = BBSIZE_512
config BBEN = OFF
config SAFEN = OFF
config WRTAPP = OFF
config WRTB = OFF
config WRTC = OFF
config WRTD = OFF
config WRTSAF = OFF
config LVP = ON
config CP = OFF
